# **Phishing Domain Detection (Data Collection & Feature Extraction)**

### **Objective : Collect data and extract necessary features from that data to train Machine Learning models**

# **1.0] Data Collection**

We'll use this kaggle dataset : https://www.kaggle.com/siddharthkumar25/malicious-and-benign-urls.

It contains 450k domain url's out of which 345k are legitimate & 104k are malicious.

From this dataset 10,000 url's are randomly collected from each class to train ML models.

In [1]:
# Check if GPU is being used.

import tensorflow as tf
tf.test.gpu_device_name()

''

In [2]:
import pandas as pd

# Loading the downloaded dataset
df = pd.read_csv("/content/drive/MyDrive/urldata.csv")
df.head(10)

   Unnamed: 0                        url   label  result
0           0     https://www.google.com  benign       0
1           1    https://www.youtube.com  benign       0
2           2   https://www.facebook.com  benign       0
3           3      https://www.baidu.com  benign       0
4           4  https://www.wikipedia.org  benign       0
5           5     https://www.reddit.com  benign       0
6           6      https://www.yahoo.com  benign       0
7           7   https://www.google.co.in  benign       0
8           8         https://www.qq.com  benign       0
9           9     https://www.amazon.com  benign       0

In [3]:
#Removing the unnamed columns as it is not necesary.
df = df.drop('Unnamed: 0',axis=1)
df.head(10)

                         url   label  result
0     https://www.google.com  benign       0
1    https://www.youtube.com  benign       0
2   https://www.facebook.com  benign       0
3      https://www.baidu.com  benign       0
4  https://www.wikipedia.org  benign       0
5     https://www.reddit.com  benign       0
6      https://www.yahoo.com  benign       0
7   https://www.google.co.in  benign       0
8         https://www.qq.com  benign       0
9     https://www.amazon.com  benign       0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450176 entries, 0 to 450175
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   url     450176 non-null  object
 1   label   450176 non-null  object
 2   result  450176 non-null  int64
dtypes: int64(1), object(2)
memory usage: 10.3+ MB

In [5]:
df.shape

(450176, 3)

In [6]:
# Printing number of legit and fraud domain urls
df["label"].value_counts()

benign       345738
malicious    104438
Name: label, dtype: int64

# **2.0] Feature Extraction**

In this step, features are extracted from the URLs dataset. In total we'll be extracting 18 features for each url in the dataset

The extracted features are categorized into :
1. Length based Features
2. Count based Features
3. Binary Features

## **2.1] Length Features**

The following features will be extracted from the URL for classification.
- Length Of Url
- Length of Hostname
- Length Of Path
- Length Of First Directory
- Length Of Top Level Domain

In [7]:
#Importing dependencies
from urllib.parse import urlparse
import os.path

# changing dataframe variable
urldata = df

In [8]:
#Length of URL (Phishers can use long URL to hide the doubtful part in the address bar)
urldata['url_length'] = urldata['url'].apply(lambda i: len(str(i)))

#Hostname Length
urldata['hostname_length'] = urldata['url'].apply(lambda i: len(urlparse(i).netloc))

#Path Length
urldata['path_length'] = urldata['url'].apply(lambda i: len(urlparse(i).path))

In [9]:
#First Directory Length
def fd_length(url):
    urlpath= urlparse(url).path
    try:
        return len(urlpath.split('/')[1])
    except:
        return 0

urldata['fd_length'] = urldata['url'].apply(lambda i: fd_length(i))

In [10]:
# printing first few rows
urldata.head(10)

                         url   label  ...  path_length  fd_length
0     https://www.google.com  benign  ...            0          0
1    https://www.youtube.com  benign  ...            0          0
2   https://www.facebook.com  benign  ...            0          0
3      https://www.baidu.com  benign  ...            0          0
4  https://www.wikipedia.org  benign  ...            0          0
5     https://www.reddit.com  benign  ...            0          0
6      https://www.yahoo.com  benign  ...            0          0
7   https://www.google.co.in  benign  ...            0          0
8         https://www.qq.com  benign  ...            0          0
9     https://www.amazon.com  benign  ...            0          0

[10 rows x 7 columns]

## **2.2] Count Features**

The following features will be extracted from the URL for classification.
- Count Of '-'
- Count Of '@'
- Count Of '?'
- Count Of '%'
- Count Of '.'
- Count Of '='
- Count Of 'http'
- Count Of 'www'
- Count Of Digits
- Count Of Letters
- Count Of Number Of Directories

In [11]:

# Count of how many times a special character appearsin url

urldata['count-'] = urldata['url'].apply(lambda i: i.count('-'))

urldata['count@'] = urldata['url'].apply(lambda i: i.count('@'))

urldata['count?'] = urldata['url'].apply(lambda i: i.count('?'))

urldata['count%'] = urldata['url'].apply(lambda i: i.count('%'))

urldata['count.'] = urldata['url'].apply(lambda i: i.count('.'))

urldata['count='] = urldata['url'].apply(lambda i: i.count('='))

urldata['count-http'] = urldata['url'].apply(lambda i : i.count('http'))

urldata['count-https'] = urldata['url'].apply(lambda i : i.count('https'))

urldata['count-www'] = urldata['url'].apply(lambda i: i.count('www'))

In [12]:
def digit_count(url):
    digits = 0
    for i in url:
        if i.isnumeric():
            digits = digits + 1
    return digits
urldata['count-digits']= urldata['url'].apply(lambda i: digit_count(i))

In [13]:
def letter_count(url):
    letters = 0
    for i in url:
        if i.isalpha():
            letters = letters + 1
    return letters
urldata['count-letters']= urldata['url'].apply(lambda i: letter_count(i))

In [14]:
def no_of_dir(url):
    urldir = urlparse(url).path
    return urldir.count('/')
urldata['count_dir'] = urldata['url'].apply(lambda i: no_of_dir(i))

In [15]:
# printing first few rows
urldata.head(10)

                         url   label  ...  count-letters  count_dir
0     https://www.google.com  benign  ...             17          0
1    https://www.youtube.com  benign  ...             18          0
2   https://www.facebook.com  benign  ...             19          0
3      https://www.baidu.com  benign  ...             16          0
4  https://www.wikipedia.org  benign  ...             20          0
5     https://www.reddit.com  benign  ...             17          0
6      https://www.yahoo.com  benign  ...             16          0
7   https://www.google.co.in  benign  ...             18          0
8         https://www.qq.com  benign  ...             13          0
9     https://www.amazon.com  benign  ...             17          0

[10 rows x 19 columns]

## **2.3] Binary Features**

The following features will be extracted from the URL for classification.
- Use of IP or not
- Use of Shortening URL or not

#### **2.3.1] IP Address in the URL**

Checks for the presence of IP address in the URL. URLs may have IP address instead of domain name. If an IP address is used as an alternative of the domain name in the URL, we can be sure that someone is trying to steal personal information with this URL.

In [16]:
import re

#Use of IP or not in domain
def having_ip_address(url):
    match = re.search(
        '(([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.'
        '([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\/)|'  # IPv4
        '((0x[0-9a-fA-F]{1,2})\\.(0x[0-9a-fA-F]{1,2})\\.(0x[0-9a-fA-F]{1,2})\\.(0x[0-9a-fA-F]{1,2})\\/)' # IPv4 in hexadecimal
        '(?:[a-fA-F0-9]{1,4}:){7}[a-fA-F0-9]{1,4}', url)  # Ipv6
    if match:
        # print match.group()
        return -1
    else:
        # print 'No matching pattern found'
        return 1
urldata['use_of_ip'] = urldata['url'].apply(lambda i: having_ip_address(i))

#### **2.3.2] Using URL Shortening Services “TinyURL”**

URL shortening is a method on the “World Wide Web” in which a URL may be made considerably smaller in length and still lead to the required webpage. This is accomplished by means of an “HTTP Redirect” on a domain name that is short, which links to the webpage that has a long URL.

In [17]:
# use of url shortening service
def shortening_service(url):
    match = re.search('bit\.ly|goo\.gl|shorte\.st|go2l\.ink|x\.co|ow\.ly|t\.co|tinyurl|tr\.im|is\.gd|cli\.gs|'
                      'yfrog\.com|migre\.me|ff\.im|tiny\.cc|url4\.eu|twit\.ac|su\.pr|twurl\.nl|snipurl\.com|'
                      'short\.to|BudURL\.com|ping\.fm|post\.ly|Just\.as|bkite\.com|snipr\.com|fic\.kr|loopt\.us|'
                      'doiop\.com|short\.ie|kl\.am|wp\.me|rubyurl\.com|om\.ly|to\.ly|bit\.do|t\.co|lnkd\.in|'
                      'db\.tt|qr\.ae|adf\.ly|goo\.gl|bitly\.com|cur\.lv|tinyurl\.com|ow\.ly|bit\.ly|ity\.im|'
                      'q\.gs|is\.gd|po\.st|bc\.vc|twitthis\.com|u\.to|j\.mp|buzurl\.com|cutt\.us|u\.bb|yourls\.org|'
                      'x\.co|prettylinkpro\.com|scrnch\.me|filoops\.info|vzturl\.com|qr\.net|1url\.com|tweez\.me|v\.gd|'
                      'tr\.im|link\.zip\.net',
                      url)
    if match:
        return -1
    else:
        return 1
urldata['short_url'] = urldata['url'].apply(lambda i: shortening_service(i))

In [18]:
# printing first few rows
urldata.head(10)

                         url   label  result  ...  count_dir  use_of_ip  short_url
0     https://www.google.com  benign       0  ...          0          1          1
1    https://www.youtube.com  benign       0  ...          0          1          1
2   https://www.facebook.com  benign       0  ...          0          1          1
3      https://www.baidu.com  benign       0  ...          0          1          1
4  https://www.wikipedia.org  benign       0  ...          0          1          1
5     https://www.reddit.com  benign       0  ...          0          1         -1
6      https://www.yahoo.com  benign       0  ...          0          1          1
7   https://www.google.co.in  benign       0  ...          0          1          1
8         https://www.qq.com  benign       0  ...          0          1          1
9     https://www.amazon.com  benign       0  ...          0          1          1

[10 rows x 21 columns]

In [19]:
# printing info about current dataset
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450176 entries, 0 to 450175
Data columns (total 21 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   url              450176 non-null  object
 1   label            450176 non-null  object
 2   result           450176 non-null  int64
 3   url_length       450176 non-null  int64
 4   hostname_length  450176 non-null  int64
 5   path_length      450176 non-null  int64
 6   fd_length        450176 non-null  int64
 7   count-           450176 non-null  int64
 8   count@           450176 non-null  int64
 9   count?           450176 non-null  int64
 10  count%           450176 non-null  int64
 11  count.           450176 non-null  int64
 12  count=           450176 non-null  int64
 13  count-http       450176 non-null  int64
 14  count-https      450176 non-null  int64
 15  count-www        450176 non-null  int64
 16  count-digits     450176 non-null  int64
 17  count-letters    450176 non-null  int64
 18  count_dir        450176 non-null  int64
 19  use_of_ip        450176 non-null  int64
 20  short_url        450176 non-null  int64
dtypes: int64(19), object(2)
memory usage: 72.1+ MB

### **Saving the dataset as .csv file**

In [20]:
urldata.to_csv("Url_Processed.csv")

## **Conclusion : The objective of this dataset is achieved,we extracted 18 features for each url in our dataset and we saved the final dataset for model training in the next notebook**